/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as EventRouteImport } from './routes/event'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ReminderRouteImport } from './routes/reminder'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TaskRouteImport } from './routes/task'
import { Route as TodayRouteImport } from './routes/today'
import { Route as MemoryIndexRouteImport } from './routes/memory.index'
import { Route as MemoryIdRouteImport } from './routes/memory.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderRoute = ReminderRouteImport.update({
  id: '/reminder',
  path: '/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskRoute = TaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIdRoute = MemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/event': typeof EventRoute
  '/household': typeof HouseholdRoute
  '/notifications': typeof NotificationsRoute
  '/reminder': typeof ReminderRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/': typeof MemoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/event': typeof EventRoute
  '/household': typeof HouseholdRoute
  '/notifications': typeof NotificationsRoute
  '/reminder': typeof ReminderRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory': typeof MemoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/event': typeof EventRoute
  '/household': typeof HouseholdRoute
  '/notifications': typeof NotificationsRoute
  '/reminder': typeof ReminderRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/task': typeof TaskRoute
  '/today': typeof TodayRoute
  '/memory/$id': typeof MemoryIdRoute
  '/memory/': typeof MemoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/event'
    | '/household'
    | '/notifications'
    | '/reminder'
    | '/review'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/task'
    | '/today'
    | '/memory/$id'
    | '/memory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/event'
    | '/household'
    | '/notifications'
    | '/reminder'
    | '/review'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/task'
    | '/today'
    | '/memory/$id'
    | '/memory'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/event'
    | '/household'
    | '/notifications'
    | '/reminder'
    | '/review'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/task'
    | '/today'
    | '/memory/$id'
    | '/memory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  EventRoute: typeof EventRoute
  HouseholdRoute: typeof HouseholdRoute
  NotificationsRoute: typeof NotificationsRoute
  ReminderRoute: typeof ReminderRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TaskRoute: typeof TaskRoute
  TodayRoute: typeof TodayRoute
  MemoryIdRoute: typeof MemoryIdRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder': {
      id: '/reminder'
      path: '/reminder'
      fullPath: '/reminder'
      preLoaderRoute: typeof ReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$id': {
      id: '/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof MemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  EventRoute: EventRoute,
  HouseholdRoute: HouseholdRoute,
  NotificationsRoute: NotificationsRoute,
  ReminderRoute: ReminderRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TaskRoute: TaskRoute,
  TodayRoute: TodayRoute,
  MemoryIdRoute: MemoryIdRoute,
  MemoryIndexRoute: MemoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
